#!/bin/bash
# MobileCount — bbox/2 sigma — all resolutions — 4 LRs × 600 epochs each
#
# Uses the density map directories already generated by C-3-Framework's
# precompute script (absolute paths, same img/+den/ structure).
#
# Sigma table (bbox/2 rule):
#   49x33      → σ=2  → .../49x33_s2
#   97x65      → σ=3  → .../97x65_s3
#   193x130    → σ=6  → .../193x130_s6
#   386x260    → σ=11 → .../386x260
#   772x519    → σ=24 → .../772x519_s24
#   1544x1038  → σ=48 → .../1544x1038_s48
#
# Batch size: 6 for all resolutions.
#
# Usage: nohup bash run_mobilecount_allres_bbox2_sweep.sh > /tmp/mobilecount_allres_bbox2.log 2>&1 &
set -e
cd /home/umrobotics/MobileCount

PYTHON=/home/umrobotics/C-3-Framework/.venv/bin/python3
C3_TENEBRIO=/home/umrobotics/C-3-Framework/datasets/Tenebrio

declare -A BBOX2_DIR
BBOX2_DIR[49x33]="49x33_s2"
BBOX2_DIR[97x65]="97x65_s3"
BBOX2_DIR[193x130]="193x130_s6"
BBOX2_DIR[386x260]="386x260"
BBOX2_DIR[772x519]="772x519_s24"
BBOX2_DIR[1544x1038]="1544x1038_s48"

BS=6  # batch size for all resolutions

RESOLUTIONS="49x33 97x65 193x130 386x260 772x519 1544x1038"
LR_LIST="1e-6 1e-5 1e-4 1e-3"

run_one() {
    local DATA_DIR=$1
    local LR=$2
    local RES=$3
    local BSIZE=$4
    local SUFFIX=$(basename "$DATA_DIR")
    local LOG="/tmp/mobilecount_${SUFFIX}_lr${LR}_600ep.log"

    echo ""
    echo "──────────────────────────────────────────────────────"
    echo "[$(date)] MobileCount  res=$RES  lr=$LR  bs=$BSIZE  wd=1e-4  600ep"
    echo "  data: $DATA_DIR → $LOG"
    echo "──────────────────────────────────────────────────────"

    $PYTHON train.py \
        --lr "$LR" \
        --batch-size "$BSIZE" \
        --weight-decay 1e-4 \
        --data-path "$DATA_DIR" \
        > "$LOG" 2>&1

    echo "[$(date)] done."

    EXP_DIR=$(ls -td exp/*_"${SUFFIX}" 2>/dev/null | head -1)
    [ -n "$EXP_DIR" ] && $PYTHON scripts/plot_training_curves.py "$EXP_DIR" 2>/dev/null || true
}

echo ""
echo "════════════════════════════════════════════════════════"
echo "[$(date)] MobileCount bbox/2 all-resolution sweep — START"
echo "Resolutions: $RESOLUTIONS"
echo "LRs: $LR_LIST"
echo "════════════════════════════════════════════════════════"

for RES in $RESOLUTIONS; do
    DIR="${C3_TENEBRIO}/${BBOX2_DIR[$RES]}"
    echo ""
    echo "╔══════════════════════════════════════════════════╗"
    echo "║  Resolution: $RES  ($(basename $DIR))  bs=$BS"
    echo "╚══════════════════════════════════════════════════╝"

    for LR in $LR_LIST; do
        run_one "$DIR" "$LR" "$RES" "$BS"
    done

    echo ""
    echo "[$(date)] ✓ $RES complete — all LRs done."
done

echo ""
echo "════════════════════════════════════════════════════════"
echo "[$(date)] ALL DONE — MobileCount bbox/2 all-resolution sweep"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Per-resolution experiments:"
for RES in $RESOLUTIONS; do
    SUFFIX="${BBOX2_DIR[$RES]}"
    echo "  $RES:"
    ls -td exp/*_"${SUFFIX}" 2>/dev/null | head -4 | sed "s/^/    /"
done
echo ""
echo "Logs: /tmp/mobilecount_*_600ep.log"
